# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - n 14.18.3
      - npm install -g npm@latest
      - echo Installing server node modules...
      - cd server
      - npm install
      - cd ..
      - echo Installing client node modules...
      - cd client
      - npm install
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - cd client
      - npm run build
      - cd ..
      - echo Formatting Resources
      - cd server
      - npm run formatPrompts
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  name: $AWS_REGION-$(date +%Y-%m-%d)